version: "3"

services:
  mysql:
    image: mysql:8
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Seoul
      - MYSQL_USER=soup
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=soup
      - MYSQL_ROOT_PASSWORD=password
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - soup

  redis:
    image: redis:6
    volumes:
      - ./data/redis:/data
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    networks:
      - soup

  minio:
    image: minio/minio
    volumes:
      - ./data/minio:/bucket
    environment:
      - MINIO_ROOT_USER=soup
      - MINIO_ROOT_PASSWORD=password
    command: server --address ":9000" --console-address ":9001" /bucket
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - soup

  create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add soup http://minio:9000 soup password;
      /usr/bin/mc mb soup/bucket;
      /usr/bin/mc policy set public soup/bucket;
      exit 0;
      "
    networks:
      - soup

networks:
  soup:
    labels:
      - soup
