server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/soup
    username: soup
    password: Y29tLmdpdGh1Yi5jZS1zb3VwLnNvdXAtc2VydmVyLm15c3FsLnBhc3N3b3JkCg

  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: redis
    port: 6379
    password: Y29tLmdpdGh1Yi5jZS1zb3VwLnNvdXAtc2VydmVyLnJlZGlzLnBhc3N3b3JkCg

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: I2NvbS5naXRodWIuc291cC5zb3VwLXNlcnZlciNjb20uZ2l0aHViLnNvdXAuc291cC1zZXJ2ZXIjY29tLmdpdGh1Yi5zb3VwLnNvdXAtc2VydmVyIwo=
  expired:
    access: 86400000
    refresh: 604800000
